### ISSUE TITLE
Please don't overload the AoC servers

### ISSUE THREAD

**Issue by topaz** [wimglenn/advent-of-code-data#1]
*Please* don't make modules like this.  This module requests the user's input every time the script runs; the Advent of Code servers aren't magic and can only handle limited capacity.  Please make your script store the player's input in a file and possibly sleep() before downloading the input to prevent someone calling get_data() in a loop.

See also: https://www.reddit.com/r/adventofcode/comments/3v64sb/aoc_is_fragile_please_be_gentle/

**Comment by wimglenn** [comment]
Hi Eric, 

Thanks for your work on AoC!  

OK, I will make v0.3 memoize the puzzle inputs and persist that data to a file storage.  

It's not really possible to prevent people abusing the site by calling get_data in a loop client-side, any counter-measure I put in would be easily reversed.  The responsibility for rate-limiting is better handled server-side.

What I can do is prevent a new request if the time of the last request was just 5~10 seconds ago.  But it would only prevent users who made stupid mistake, it's unlikely going to stop a malicious user that wants to DoS you.  Let me know what you think.  

Thanks and regards,
Wim

**Comment by topaz** [comment]
I'm not trying to stop malicious users; they have substantially better ways of executing an attack than your library.  I'm trying to avoid beginners (of whom there are many doing AoC) from thinking they'll be clever and stick the method in a loop without realizing the implications.

I just posted a new thread on the subreddit since I'm seeing libraries like this more frequently lately:

https://www.reddit.com/r/adventofcode/comments/5gefzc/only_you_can_prevent_ddos_attacks_on_aoc/

**Comment by wimglenn** [comment]
@topaz  [The latest release includes](https://github.com/wimglenn/advent-of-code-data/commit/f142bb04c32f49003db6a48768445830ce515c25) client-side rate limiting on `get_data` (1 request per 10 seconds) and saves the inputs to disk for later re-use.  Please have a look at it and let me know if it addresses all your concerns.  If there are no further changes needed, you may close this issue.   Cheers 🍺

**Comment by topaz** [comment]
One more minor change: if this is going to be widely deployed in places like pypi, please set a unique user agent so this library can be identified in my logs.

**Comment by topaz** [comment]
Looks great!
