### ISSUE TITLE
Using the oop interface just prints the description of part 1 

### ISSUE THREAD

**Issue by jolitti** [wimglenn/advent-of-code-data#107]
I don't know why, but at some point in the last few days the Puzzle class broke for me.
If I run the script at https://github.com/jolitti/adventofcode/blob/main/2022/day16.py (both with aocd version 1.3.1 and 1.3.2) it just prints the description of the problem to the terminal without attempting to submit the solution.

Has the aoc API changed lately?

**Comment by wimglenn** [comment]
Nothing has changed in API, it sounds very likely that your with token(s) expired.

Check with

    aocd-token —check

**Comment by jolitti** [comment]
Thank you, this solved the issue
