### ISSUE TITLE
Wrong reference test data for 2023/12/14

### ISSUE THREAD

**Issue by Xaelias** [wimglenn/advent-of-code-data#134]
Hey,
Not sure if this is the best place to report, and maybe it's been reported before (I don't know where to check outside of here).

For [2023/12/14](https://adventofcode.com/2023/day/14), `aocd 2023 14 -e` yields:
```
                    --- Day 14: Parabolic Reflector Dish ---
                      https://adventofcode.com/2023/day/14
------------------------------- Example data 1/1 -------------------------------
O....#....
O.OO#....#
.....##...
OO.#O....O
.O.....O#.
O.#..O.#.#
..O..#O..O
.......O..
#....###..
#OO..#....
--------------------------------------------------------------------------------
answer_a: 136
answer_b: 1000000000
--------------------------------------------------------------------------------
```
Which is wrong.

`answer_b` should be `64`. (`1000000000` was obviously the number of cycles)

**Comment by wimglenn** [comment]
Actually this was already fixed yesterday. You'll want to `pip install -U aocd-example-parser` to get the latest version.

**Comment by Xaelias** [comment]
Hmm yeah I was up to date but the CLI still returns the wrong thing. The underlying file seem to have the correct data so either it's a caching issue somewhere or maybe I'm doing smth wrong.
But that's fine I'll figure it out. As long as you're aware :-)

**Comment by wimglenn** [comment]
Are you sure you're up to date on `advent-of-code-data` or on `aocd-example-parser`? They are different packages, the example parser implementation is provided by a plugin package.

**Comment by Xaelias** [comment]
Ok I uninstalled and reinstalled everything. There must have been something weird happening with my environment. Thanks for fixing it!
