### ISSUE TITLE
2 Errors when running "Verify multiple different inputs" on Windows

### ISSUE THREAD

**Issue by JimmyCarlos** [wimglenn/advent-of-code-data#20]
Hi, 
Having completed all the days from the Advent of Code, the multiple different inputs feature seems really interesting and fun.  I am trying to get the "Verify your code against multiple different inputs" feature working on Windows 8.1 in a cmd.exe, but am getting stuck with errors.

Output:
``
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.
C:\Windows\System32>aoc --years 2019 --day 1
  22.01s   2019/1  - The Tyranny of the Rocket Equation                wim/google   /RuntimeError: I/O operations still in flight while destroying Overlapped object, the process may crash
  22.11s   2019/1  - The Tyranny of the Rocket Equation                wim/google   N ImportError("Error while finding module specificat
   0.41s   2019/1  - The Tyranny of the Rocket Equation                wim/github   -RuntimeError: I/O operations still in flight while destroying Overlapped object, the process may crash
   0.51s   2019/1  - The Tyranny of the Rocket Equation                wim/github   N ImportError("Error while finding module specificat
   0.99s   2019/1  - The Tyranny of the Rocket Equation         myusername/google   -RuntimeError: I/O operations still in flight while destroying Overlapped object, the process may crash
   1.09s   2019/1  - The Tyranny of the Rocket Equation         myusername/google   ? part a: 1234 (correct answer is unknown)   ? part b: 5678 (correct answer is unknown)
   0.39s   2019/1  - The Tyranny of the Rocket Equation         myusername/github   /RuntimeError: I/O operations still in flight while destroying Overlapped object, the process may crash
   0.49s   2019/1  - The Tyranny of the Rocket Equation         myusername/github   N part a: 1234 (expected: 3305115)         N part b: 5678 (expected: 4954799)
`
My Actions to this point:

Install Latest advent-of-code module: pip install advent-of-code-data --upgrade
Create tokens file with github and google at: {USER}\.config\aocd\tokens.json
Install sample master:   pip install advent-of-code-sample (Identical issue is caused when I download the folder from github then do pip install {PATH_TO_SAMPLE_MASTER}
Install the wimcode: pip install advent-of-code-wim
Launch cmd.exe with admin privileges and run: aoc --years 2019 --days 1

I'm running Python 3.5. Let me know if you'd like any other information. Thanks for your time in reading this.

**Comment by wimglenn** [comment]
You don't need to install `advent-of-code-wim` nor `advent-of-code-sample`.  The former is my solution code, and the latter is just an example repository demonstrating how to write an entry point for the runner. You should be writing your own entry point and installing that one.

**Comment by JimmyCarlos** [comment]
Thank you for your comment wim. You were right, I shouldn't have done pip install advent-of-code-wim. Instead, I downloaded and unzipped the code from https://github.com/wimglenn/advent-of-code-wim and then pip install "...\Advent of Code\advent-of-code-wim-master"

Doing so gets the code to run, but still leaves one error, here's the new output.

C:\Windows>aoc --years 2019 --days 1

   5.28s   2019/1  - The Tyranny of the Rocket Equation         wim/google   /RuntimeError: I/O operations still in flight while destroying Overlapped object, the process may crash

   5.38s   2019/1  - The Tyranny of the Rocket Equation         wim/google   Y part a: 3380880                          Y part b: 5068454

   1.21s   2019/1  - The Tyranny of the Rocket Equation         wim/github   \RuntimeError: I/O operations still in flight while destroying Overlapped object, the process may crash

   1.31s   2019/1  - The Tyranny of the Rocket Equation         wim/github   Y part a: 3305115                          Y part b: 4954799

It seems it is outputting a RunTimeError at 0.1 seconds before finishing on every try. Is there something else silly I am doing/not doing? Thanks again for your help, I have nearly no experience in using shell commands.

**Comment by wimglenn** [comment]
I think there may be a problem with [pebble](https://github.com/noxdafox/pebble/issues/21) on Windows platform. I don't use Windows so I can't check this right now. Next time I'm near a Windows box I'll take a look.

**Comment by JimmyCarlos** [comment]
You're correct again. I updated Pebble from 4.3.9 to 4.4.0 and the problem resolved itself! I deliberately hadn't updated Pebble to 4.4.1 as it won't install on my system. Nice work wim!
