### ISSUE TITLE
add more conveniences (lines, numbers)

### ISSUE THREAD

**Issue by wimglenn** [wimglenn/advent-of-code-data#25]
I keep needing these so...

```
from aocd import data  # string
from aocd import lines  # list
from aocd import numbers  # list or array of numbers
```

**Comment by aadibajpai** [comment]
is, for example `lines`, just an abstraction over data?

so roughly equivalent to `data.splitlines()` while numbers would be `[int(line) for line in lines]` I assume?

**Comment by wimglenn** [comment]
@aadibajpai yep, you guessed it

**Comment by wimglenn** [comment]
now avail in advent-of-code v0.9.0
