### ISSUE TITLE
Filenames don't seem to be extracted properly

### ISSUE THREAD

**Issue by bmintz** [wimglenn/advent-of-code-data#3]
For the life of me I can't get this working.

Here's what I've tried:

```python
from aocd import data

print(data)
```

Directory for all examples is ~/code/by-language/python/3/adventofcode/2017/13. With a directory like that, you'd think any filename would work, right? Wrong. Here are the filenames I've tried.
- firewall.py
- test.py
- 13.py
- q13.py
- 2017_13.py
- xmas_problem_2016_25b_dawg.py
- xmas_problem_2017_13_dawg.py
- year_2017_day_13.py

All print None. What should I do?

**Comment by bmintz** [comment]
Since `[n] = re.findall(pattern_day, filename)` only allows one number in the directory, I tried ~/code/by-language/python/adventofcode/2017/13 and that didn't work either.

**Comment by wimglenn** [comment]
@bmintz   If there are no digits in the filename, that frame will be skipped.  This rules out `test.py` and `firewall.py`.  Most of the other examples in your post should work in release v0.4.2, I've tweaked the logic a little to allow your directory structure (multiple numbers are now ok, as long as they are the _same_ number - so best to keep the /3/ segment out of the path).  

Please `pip install --upgrade advent-of-code-data` and try again.

**Comment by bmintz** [comment]
I made it so that only the last number is kept
