### ISSUE TITLE
import aocd

### ISSUE THREAD

**Issue by balshetzer** [wimglenn/advent-of-code-data#35]
`import aocd` results in AttributeError. Is that intended?

**Comment by wimglenn** [comment]
No this is not intended. Please produce a reproducible example?

**Comment by balshetzer** [comment]
How would you like the example? I just created a file called `7a.py` with `import aocd` in it and got the error from __init__.py line 73. All the examples have something like `from aocd import foo` so maybe I should have done that instead.

**Comment by wimglenn** [comment]
Well, day 7 data is not available yet.  Try `6a.py` instead :)

**Comment by balshetzer** [comment]
I see the problem now. I was trying to use an unexported function in my code (get_day_and_year: I was trying to see how it works). I'd like to suggest changing line 73 to say `raise AttributeError(name)`. I can send a PR if you prefer.

**Comment by wimglenn** [comment]
I've released v0.9.2 with your suggestion, thanks for the contribution.

For the record `from aocd.get import get_day_and_year` should have worked fine - but note that that function is unlikely to be of much utility for users, more for the use of aocd itself.
