### ISSUE TITLE
Different directories for token.json and data storage

### ISSUE THREAD

**Issue by cqkh42** [wimglenn/advent-of-code-data#55]
To help keep clean directories, is it possible to add a separate env variable for the location of the tokens.json file? This would allow a user to use separate directories for configuration and data. 

 It looks like this should just be one change in the runner, I'm happy to raise a PR?

**Comment by wimglenn** [comment]
As long as it falls back to using `AOCD_DIR` for backwards compat, that's fine

**Comment by cqkh42** [comment]
Thanks, I've raised #56, let me know your thoughts
