### ISSUE TITLE
Change to use HTTPS over HTTP

### ISSUE THREAD

**Issue by cbondurant** [wimglenn/advent-of-code-data#6]
Errors with incorrect auth occurs because uri does not use HTTPS for its protocol. 

Messages always returned the prompt, rather than the proper response, this was fixed for me upon changing uri to utilize https. 

I'd make a pull request but honestly a one-liner doesn't really need that kind of attention.

**Comment by wimglenn** [comment]
@cbondurant [v0.5.1 pushed to PyPI using https now](https://files.pythonhosted.org/packages/97/75/24ae797bf433169d764391918e2ffddc037d00d08db9c01c04a1b0d47b4b/advent_of_code_data-0.5.1-py2.py3-none-any.whl)
