### ISSUE TITLE
auto-parse input with 'best' possible parser

### ISSUE THREAD

**Issue by atrejut** [wimglenn/advent-of-code-data#64]
This is a Feature Request:

currently I need to know what the data looks like before I can write my import statement.
For example, today (2021-12-02) doing
`from aocd import numbers` gives me a `ValueError` because the import can't be parsed as `numbers`.

What I'd like is something like `from aocd import parsed_data` which would go through the different parsers in some pre-defined order (strongest to weakest, ie currently numbers, then lines, then raw data), and return the first one that can parse the data successfully.

**Comment by wimglenn** [comment]
Interesting idea. My concern is that the format of the input data is often too arbitrary to do something useful here without risk of ambiguity, and that in many cases it's up to the user's own preference exactly what structures they want to parse raw data into.

However you could do this on your own side, something like:

```
# mymodule.py
from aocd.get import get_data, get_day_and_year
day, year = get_day_and_year()
raw_data = get_data(year=year, day=day)
for parser in parsers:
    try:
        parsed_data = parser(raw_data)
    except Exception:
        pass
    else:
        break
else:
    parsed_data = raw_data

```

And now you could use `from mymodule import parsed_data`. Let me know how it goes.

**Comment by atrejut** [comment]
> My concern is that the format of the input data is often too arbitrary to do something useful here without risk of ambiguity, 

absolutely, I don't think this would be (or ever involve into) something that **always** works, more a 'let's see if this happens to work, and if not I'm no worse of than without it' kind of thing. With just the two current parsers I think the order would be pretty clear, and the logic simple enough, but with more parsers I agree that it might become a bit of a mess.

> and that in many cases it's up to the user's own preference exactly what structures they want to parse raw data into.

well, it would default to the raw data if none of the parsers succeed, right? The assumption would be that if any of the parsers can actually parse the data, that would (almost) always be preferable to the raw data (and if not you could still do `from aocd import data`).

 Anyways, I'm fine with rolling my own, just thought I'd throw the suggestion out there. So feel free to just close if you don't like it :)

**Comment by wimglenn** [comment]
My point was more that what a successful parse looks like depends on what you want to do with the data, which in turn depends on the individual user's coding style and what their plan of attack for solving the problem is going to be.  e.g. one person might want to use a list of pairs, another person might prefer a dict. 

So I think it's best to leave this part up to the user to define their own post-processing if they want to.
