### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by mathstrains21** [wimglenn/advent-of-code-data#66]
Hi! Is there a chance that this library could also get the example data?

**Comment by wimglenn** [comment]
I've considered it originally, unfortunately the location of the example data and answers is not so easily detectable. Some problems don't offer any examples at all! 

I'll take another look at this, perhaps it can be possible for the library to make some best-effort attempt to get the example(s) without guaranteeing that it will work correctly 100% of the time.
