### ISSUE TITLE
"submit" feature doesn't seem to work?

### ISSUE THREAD

**Issue by AWice** [wimglenn/advent-of-code-data#7]
When I do a submit, I get a RESPONSE OK but nothing actually happens, and I still need to submit manually on the site.  I was submitting the correct answers.  Was this feature disabled for some reason?  I see some indication of that in the other issue threads.

**Comment by wimglenn** [comment]
I used automated submit for both parts 1 and 2 yesterday without issue. Which version of lib do you have installed? v0.5.1 is current.

**Comment by AWice** [comment]
Doesnt work 0.5, works 0.5.1, update faq please
