### ISSUE TITLE
Why can't days have a leading zero for frame inspector date finder?

### ISSUE THREAD

**Issue by joshcoales** [wimglenn/advent-of-code-data#73]
https://github.com/wimglenn/advent-of-code-data/blob/b948c3482fb4e1d513a13674606c567ba585c887/aocd/get.py#L135

I mean, I suppose it will still work and match files named "2021/02.py", it'll just match that 2 rather than 02, but I don't see why that assertion exists?

More of a question than an issue, as I realised while writing this that zero-padded filenames will still work

**Comment by wimglenn** [comment]
It’s a check on the programmer’s logic, not a check on the data. If day was ever containing a string with a leading zero at this stage, then I’ve overlooked something, and likely have a bug here or have made an incorrect assumption.

I’ll never use asserts to validate data (except in tests), instead they’re more like a “loaded comment”. In this case, the assert is saying that the regex pattern defined above should eliminate any the possibility of a leading zero in the capture group.

**Comment by joshcoales** [comment]
Ah, okay, it's just a check to ensure you don't change that in future without updating the asserts, got it!
thank you
