### ISSUE TITLE
Allow choosing user by identifier in tokens.json

### ISSUE THREAD

**Issue by tomribbens** [wimglenn/advent-of-code-data#76]
When the runner gives an error on a specific input, I would like to be able to switch to work on that quickly. The way I'm doing it currently is by adding user=User(token=<token>) to the Puzzle constructor. However, this could be made much cleaner if it supported the identifiers in tokens.json. This would also mean the cookie token will not likely appear in code that is sent to github.

**Comment by wimglenn** [comment]
@tomribbens  Sounds reasonable. [`v1.1.3`](https://pypi.org/project/advent-of-code-data/1.1.3/) adds support for that, usage is like `User.from_id("github.wim.123456")` where the id is a string key from the `tokens.json`.
