### ISSUE TITLE
Include type information

### ISSUE THREAD

**Issue by cj81499** [wimglenn/advent-of-code-data#78]
I like to type check my Python code with [mypy](https://mypy.readthedocs.io), but this library doesn't provide any type hints.

See [PEP 561](https://peps.python.org/pep-0561/) for more info.

I haven't contributed types to a library before, but I may give it a shot myself if you're open to contributions from others.

**Comment by wimglenn** [comment]
I don’t use mypy but I’m not against it if someone else wants to make it work. We do still support Python 2, though, because in several problem cases for advent of code pypy2 is still significantly faster than any Python 3.X

**Comment by cj81499** [comment]
Sure thing! I've actually already started on this locally and hope to push to my fork soon.

I've been using "inline" (Python 3) style hints (it's much easier to write them this way), but I'll have to revise it to use type stubs before merge (or, drop python 2 support, but it's totally reasonable to prefer to keep compatibility).
