### ISSUE TITLE
expose functions in cookies.py

### ISSUE THREAD

**Issue by nhomble** [wimglenn/advent-of-code-data#82]
# Problem I would like solved

I'd like to use this library within a jupyter notebook. As part of that, I'd like to be able to programmatically pull in my `AOC_SESSION` from a previous cell.

I'd like to stay within my notebook rather than running the cookies cli separately.

# Describe the ideal solution

If the extraction logic were exposed in `cookies.py`, I could run a function like `def extract_tokens()` to make everything explicit and I could pass my session directly.

While `scrape_session_tokens()` is an exposed function, it does too much (`argparse` especially) that makes it incompatible with the notebook.

# Alternatives and current work-arounds

I gotta do things outside of the notebook :/

**Comment by wimglenn** [comment]
Take a look at the refactor in #83. Is that sufficient?

**Comment by nhomble** [comment]
Damn that was fast 😄 I think we extracted the same bit of code. I was going to submit this: https://github.com/nhomble/advent-of-code-data/commit/7d50a74dcdc8010e1e654d73ee5b01fe8605c5c0.

I'll take a look at yours and won't a pr myself.
