### ISSUE TITLE
Include contact information in the user agent, otherwise it will be blocked

### ISSUE THREAD

**Issue by pedrosorio** [wimglenn/advent-of-code-data#90]
https://www.reddit.com/r/adventofcode/comments/z9dhtd/please_include_your_contact_info_in_the_useragent/

**Comment by wimglenn** [comment]
We already set a user-agent [since 2016](https://github.com/wimglenn/advent-of-code-data/commit/bcf2dacafdf37622e5bd9797e24ff7f8bf853dce) (aocd v0.3.1)

But in #91 (v1.2.3) I'll make it match the format topaz suggests in that reddit post exactly
