### ISSUE TITLE
filename date extraction magic fails when run from jupyterlab / .ipynb file

### ISSUE THREAD

**Issue by atrejut** [wimglenn/advent-of-code-data#92]
Hi there,

I've been using aocd with a simple `from aocd import data` in the past. However, this year, that fails with `AocdError: Failed introspection of day` -- even though I did not change the structure of the filename.

Now, I did a tiny bit of digging, and it seems the problem is in `get_day_and_year()` which finds a stack frame like

```
stack crawl found /var/folders/mc/tp4bg6ld1_38smzn0c6xpwmh0000gn/T/ipykernel_2298/3755599408.py
```
which it clearly can't extract the current date from :)
It seems to me that this is the last stack frame to consider, if I add something like `'ipyk' in name` to the `reasons_to_skip_frame` it jumps into the REPL branch.

I suspect (but did not verify) that this is to do with the version of ipython/jupyter-lab I'm running?

For reference that is 
- python == 3.10.8
- ipython == 8.6.0
- ipykernel == 6.17.1
- jupyterlab == 3.4.2
  
Happy to assist if there's anything more I can do to debug the issue :)

Thanks!

Atreju

**Comment by wimglenn** [comment]
Hi @atrejut, hmm, what is the filename where you have the import statement, and what other filenames are in the stack at that point? Could you stick a `print("\n".join(stack))` in after [this line](https://github.com/wimglenn/advent-of-code-data/blob/e66f0fe58893a59e56a4857c7687ea434ed63147/aocd/get.py#L99) and tell me what you see?

**Comment by wimglenn** [comment]
All the .mambaforge filenames are clearly library code - but I don't know what the last frame with the scratch looking filename is - what are the contents of "/var/folders/mc/tp4bg6ld1_38smzn0c6xpwmh0000gn/T/ipykernel_3953/371372384.py", does it have your puzzle code in it?  I wonder if Jupyter is copying the code from your .ipynb into a temporary file with a randomly generated filename, and previous versions may have used something resembling the original file name.
I'll try and get this running locally to reproduce, it's a conda env right?

**Comment by atrejut** [comment]
> I wonder if Jupyter is copying the code from your .ipynb into a temporary file with a randomly generated filename, and previous versions may have used something resembling the original file name.

It sure looks that way -- but if so the file is very ephemeral. It doesn't seem to exist (in fact the `ipykernel_XXXX`-subfolders don't seem to exist). The kernel is still running though.

It is effectively a conda env, yes `mamba` is a re-implementation (?) of conda with kinder license terms.

**Comment by wimglenn** [comment]
I can reproduce this! I have no idea how to fix it though. Even from the stack frame I'm not finding any link back to the .ipynb filename. And the ipykernal_*.py file is gone as soon as I try to look at it.

**Comment by wimglenn** [comment]
@atrejut Could you check this in your env pls?
```
import logging
fmt = "filename=%(filename)s module=%(module)s pathname=%(pathname)s %(msg)s"
logging.basicConfig(format=fmt, level=logging.DEBUG, force=True)
logging.debug("hello world!!")
```

**Comment by atrejut** [comment]
nice -- yes, can confirm that works for me! 

for the record:
I needed to install jupyter-server into the env, that's probably because I usually just have jupyterlab running in one central env, and just using kernels from other envs. So each env usually only has ipython installed, but not jupyter. I think it's totally reasonable to expect/require users to have jupyter-server installed into the aoc-env though :)

**Comment by wimglenn** [comment]
I added an "extra" to pull in the jupyter-server optional deps.

    pip install 'advent-of-code-data[nb]>=1.3.0'
