### ISSUE TITLE
Proxy not used

### ISSUE THREAD

**Issue by meridani** [wimglenn/advent-of-code-data#94]
When behind proxy aocd can't download anything from the website.

  File "C:\Users\x\AppData\Roaming\Python\Python310\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\x\AppData\Roaming\Python\Python310\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\x\AppData\Roaming\Python\Python310\site-packages\requests\adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='adventofcode.com', port=443): Max retries exceeded with url: /settings (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required')))

**Comment by wimglenn** [comment]
How are you configuring proxy?

**Comment by meridani** [comment]
By using the environment variables http_proxy and https_proxy. I'm on windows.

**Comment by wimglenn** [comment]
This is outside of scope for `advent-of-code-data` I think, as long as the `HTTP_PROXY` / `HTTPS_PROXY` env vars are set `requests` module should just use them, with no extra configuration required for aocd.

I'm going to close this, but if you can provide a reproducible example showing a proxy configuration which works to https://example.org/ but fails to https://adventofcode.com/ I'll take another look.
