### ISSUE TITLE
No name "Puzzle" in module "aocd"

### ISSUE THREAD

**Issue by jolitti** [wimglenn/advent-of-code-data#95]
I installed this module on python3.10 with pip and `get_data` works correctly, but `Puzzle` (along with `lines` and `numbers`) is not recognized as part of the module. What could be causing this error?

**Comment by wimglenn** [comment]
The `Puzzle` type is not at the top-level, it would be `from aocd.models import Puzzle`.
For the others, I'll need some more context...
What advent-of-code-data version? (check with pip list)
What output do you see for `python3 -c 'from aocd import lines'`?

**Comment by jolitti** [comment]
The wrong `Puzzle` import is my bad

My aocd version is 1.3.0
The inline import works, but when I try to write it into a file with vim i get a pylint error (no name "lines" in module "aocd") and when I run it I get a "Failed introspection of filename"

**Comment by wimglenn** [comment]
pylint is a blunt tool and can be ignored.  data, lines etc are dynamically created so they can not be found by static analysis tools.

What filename are you using? It needs to have recognizable year/day in the filename/path like `puzzle-2022-01.py` or `2022/day1.py` or something like that.

**Comment by jolitti** [comment]
My current repo looks like this: `adventofcode`/`2022`/`02`/`main.py`. I elected to keep each file in a separate folder becase I also wanted to save the input data in a file, but knowing this I'll try restructuring it

**Comment by wimglenn** [comment]
Aha, yes that would explain it - it would not work currently because the introspection currently ignores frames when the .py file does not have digits in it, and `main.py` does not have digits. However, I think your structure is actually quite fine, since the year and month are unambiguously found in the absolute path. I'll update aocd to detect this case properly.

**Comment by wimglenn** [comment]
@jolitti  Please try out aocd v1.3.1 , I've updated it so that it should work with a directory structure like adventofcode/2022/02/main.py

**Comment by jolitti** [comment]
Thank you very much! Have fun with this year's aoc
